### ISSUE TITLE
🐛I can't install it

### ISSUE THREAD

**Issue by Fitsoldecot** [RiversideValley/Emerald#37] opened 2024-07-09 20:51 UTC
### ⏱️ Before you start...

- [X] Are you on the latest version of Emerald? You might be using an old version.
- [X] Have you checked whether or not a similar issue has already been reported?

### 🪟 What build of Windows is this issue present? (optional)

Windows 11 build 22631.3810

### 🔢 What version of Emerald are you on?

0.7.9

### 📄 Description

I can't install Emerald because there is an error with the installation package certificate

### 🪜 Steps To Reproduce

1. Download the msixbundle
2. Try to install it

### 🤔 Expected behavior

I was waiting for the installation to complete and be able to use Emerald, which it didn't.

### 📸 Assets

![emeraldbug](https://github.com/RiversideValley/Emerald/assets/175072531/ccf885b7-f001-431a-b23e-fca68a98f577)
The translation (I used Google Translate lol):
![emeraldbug (1)](https://github.com/RiversideValley/Emerald/assets/175072531/088255e4-0710-4ee9-bb1f-2bba85af124d)

**Comment by Lamparter** [comment] 2024-07-11 16:26
Duplicate of #35

**Closed by Lamparter** 2024-07-11 16:26 UTC
Labels: bug
